### YamlMime:ManagedReference
items:
- uid: Discord.Commands.CommandException
  commentId: T:Discord.Commands.CommandException
  id: CommandException
  parent: Discord.Commands
  children:
  - Discord.Commands.CommandException.#ctor(Discord.Commands.CommandInfo,Discord.Commands.ICommandContext,Exception)
  - Discord.Commands.CommandException.Command
  - Discord.Commands.CommandException.Context
  langs:
  - csharp
  - vb
  name: CommandException
  nameWithType: CommandException
  fullName: Discord.Commands.CommandException
  type: Class
  source:
    remote:
      path: src/Discord.Net.Commands/CommandException.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: CommandException
    path: ../src/Discord.Net.Commands/CommandException.cs
    startLine: 7
  assemblies:
  - Discord.Net.Commands
  namespace: Discord.Commands
  summary: "\nThe exception that is thrown if another exception occurs during a command execution.\n"
  example: []
  syntax:
    content: 'public class CommandException : Exception'
    content.vb: >-
      Public Class CommandException
          Inherits Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Discord.Commands.CommandException.Command
  commentId: P:Discord.Commands.CommandException.Command
  id: Command
  parent: Discord.Commands.CommandException
  langs:
  - csharp
  - vb
  name: Command
  nameWithType: CommandException.Command
  fullName: Discord.Commands.CommandException.Command
  type: Property
  source:
    remote:
      path: src/Discord.Net.Commands/CommandException.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: Command
    path: ../src/Discord.Net.Commands/CommandException.cs
    startLine: 10
  assemblies:
  - Discord.Net.Commands
  namespace: Discord.Commands
  summary: 'Gets the command that caused the exception. '
  example: []
  syntax:
    content: public CommandInfo Command { get; }
    parameters: []
    return:
      type: Discord.Commands.CommandInfo
    content.vb: Public ReadOnly Property Command As CommandInfo
  overload: Discord.Commands.CommandException.Command*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Discord.Commands.CommandException.Context
  commentId: P:Discord.Commands.CommandException.Context
  id: Context
  parent: Discord.Commands.CommandException
  langs:
  - csharp
  - vb
  name: Context
  nameWithType: CommandException.Context
  fullName: Discord.Commands.CommandException.Context
  type: Property
  source:
    remote:
      path: src/Discord.Net.Commands/CommandException.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: Context
    path: ../src/Discord.Net.Commands/CommandException.cs
    startLine: 12
  assemblies:
  - Discord.Net.Commands
  namespace: Discord.Commands
  summary: 'Gets the command context of the exception. '
  example: []
  syntax:
    content: public ICommandContext Context { get; }
    parameters: []
    return:
      type: Discord.Commands.ICommandContext
    content.vb: Public ReadOnly Property Context As ICommandContext
  overload: Discord.Commands.CommandException.Context*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Discord.Commands.CommandException.#ctor(Discord.Commands.CommandInfo,Discord.Commands.ICommandContext,Exception)
  commentId: M:Discord.Commands.CommandException.#ctor(Discord.Commands.CommandInfo,Discord.Commands.ICommandContext,Exception)
  id: '#ctor(Discord.Commands.CommandInfo,Discord.Commands.ICommandContext,Exception)'
  parent: Discord.Commands.CommandException
  langs:
  - csharp
  - vb
  name: CommandException(CommandInfo, ICommandContext, Exception)
  nameWithType: CommandException.CommandException(CommandInfo, ICommandContext, Exception)
  fullName: Discord.Commands.CommandException.CommandException(Discord.Commands.CommandInfo, Discord.Commands.ICommandContext, Exception)
  type: Constructor
  source:
    remote:
      path: src/Discord.Net.Commands/CommandException.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: .ctor
    path: ../src/Discord.Net.Commands/CommandException.cs
    startLine: 22
  assemblies:
  - Discord.Net.Commands
  namespace: Discord.Commands
  summary: "\nInitializes a new instance of the <xref href=\"Discord.Commands.CommandException\" data-throw-if-not-resolved=\"false\"></xref> class using a\n<code data-dev-comment-type=\"paramref\" class=\"paramref\">command</code> information, a <code data-dev-comment-type=\"paramref\" class=\"paramref\">command</code> context, and the exception that\ninterrupted the execution.\n"
  example: []
  syntax:
    content: public CommandException(CommandInfo command, ICommandContext context, Exception ex)
    parameters:
    - id: command
      type: Discord.Commands.CommandInfo
      description: The command information.
    - id: context
      type: Discord.Commands.ICommandContext
      description: The context of the command.
    - id: ex
      type: Exception
      description: The exception that interrupted the command execution.
    content.vb: Public Sub New(command As CommandInfo, context As ICommandContext, ex As Exception)
  overload: Discord.Commands.CommandException.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Discord.Commands
  commentId: N:Discord.Commands
  name: Discord.Commands
  nameWithType: Discord.Commands
  fullName: Discord.Commands
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Discord.Commands.CommandException.Command*
  commentId: Overload:Discord.Commands.CommandException.Command
  name: Command
  nameWithType: CommandException.Command
  fullName: Discord.Commands.CommandException.Command
- uid: Discord.Commands.CommandInfo
  commentId: T:Discord.Commands.CommandInfo
  parent: Discord.Commands
  name: CommandInfo
  nameWithType: CommandInfo
  fullName: Discord.Commands.CommandInfo
- uid: Discord.Commands.CommandException.Context*
  commentId: Overload:Discord.Commands.CommandException.Context
  name: Context
  nameWithType: CommandException.Context
  fullName: Discord.Commands.CommandException.Context
- uid: Discord.Commands.ICommandContext
  commentId: T:Discord.Commands.ICommandContext
  parent: Discord.Commands
  name: ICommandContext
  nameWithType: ICommandContext
  fullName: Discord.Commands.ICommandContext
- uid: Discord.Commands.CommandException
  commentId: T:Discord.Commands.CommandException
  name: CommandException
  nameWithType: CommandException
  fullName: Discord.Commands.CommandException
- uid: Discord.Commands.CommandException.#ctor*
  commentId: Overload:Discord.Commands.CommandException.#ctor
  name: CommandException
  nameWithType: CommandException.CommandException
  fullName: Discord.Commands.CommandException.CommandException
- uid: Exception
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: Exception
